### ISSUE TITLE
layout加载完文件不继续执行代码的问题

### ISSUE THREAD

**Issue by zhangxuanru** [pinguo/php-msf#107]
views目录结构如下：
    public
         ----Header.php
       ----- Footer.php
    index
        ---- Index.php

Header.php具体内容如下:

  <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">	
    <title>KoolTubeeew666666666 this is a test</title> 
</head>

Index.php具体内容如下：

<?php  $this->layout('Public/Header') ?>
<body>
<header>
	
	<nav id="top">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6">
					<strong>Welcome to KOOLTUBE!</strong>
				</div>
				<div class="col-md-6 col-sm-6">
					<ul class="list-inline top-link link">
						<li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
						<li><a href="contact.html"><i class="fa fa-comments"></i> Contact</a></li>
						<li><a href="#"><i class="fa fa-question-circle"></i> FAQ</a></li>
					</ul>
				</div>
			</div>
		</div>
	</nav>
        

重启server.php后，在浏览器上显示结果如下：
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">
	
    <title>KoolTubeeew666666666 this is a test</title> 
</head>

Index.php中layout下面的内容没执行。

**Comment by pinguo-fengxingchao** [comment]
根据plates的[layouts](http://platesphp.com/templates/layouts/)文档。
如果你的目的是在index.php中插入footer.php/header.php
那么你应该使用的API是`$this->insert("filename");`来完成。而不是使用layout函数。
具体如下:
```php
// index.php
<?php $this->insert("Public/Index");?>
我是index.php中的其他内容..
<?php $this->insert("Public/Footer");?>
```
通常使用layout的话，因为layout是放在最后去渲染的(`since the layout template is actually rendered second. Typically it’s placed at the top of the file.`)
你应该要做的是在layout指定的那个文件中去用$this->section来读取你之前渲染好的内容。
对于本例子。
你的做法可以在Public中新增一个template.php作为你最后用的模版
```php
// template.php
// can insert footer/header
<?=$this->section("content");?>
```
然后在你的index.php中第一行写成:
```php
$this->layout("Public/template");
```

希望我描述清楚了。
