### ISSUE TITLE
docker 镜像问题

### ISSUE THREAD

**Issue by moyee** [pinguo/php-msf#117]
1、使用alpinelinux 进行重新打 (内核4.x了，但是无论是编译安装swoole 还是通过pcel安装swoole 都回出现找不到 libaio 事事上已经安装了)
2、使用centos7 进行制作（1.1 G ）

**Comment by pinguo-niulingyun** [comment]
1.  我们线上没有使用alpinelinux，为了保证环境的一致性，所以使用Centos6
2. 由于是开发环境，里面的开发套件很多，所以体积也比较大，具体有哪些套件，可以查看 [https://github.com/pinguo/php-msf-docker/blob/master/README.md#latest](https://github.com/pinguo/php-msf-docker/blob/master/README.md#latest)
