### ISSUE TITLE
文档都打不开！！！

### ISSUE THREAD

**Issue by sunyang3721** [pinguo/php-msf#142]
文档总是打不开。。  有没有别的地方能看的文档吗？

**Comment by xudianyang** [comment]
加PHP-MSF#1群(QQ): 614054288，有网友共享的离线版本。

**Comment by shellvon** [comment]
除了在原 Gitbook 上看 [php-msf-docs](https://www.gitbook.com/book/pinguo/php-msf-docs/details)
你至少还有以下4种方式可以看到:
- Github上可以直接阅读
- 网友提供的[国内看云](https://www.kancloud.cn/ptbird/phpmsfdoc)(可能更新不是那么及时)
- QQ群内有共享离线版 PDF, QQ群: 614054288 [![PHP-MSF#1群](https://pub.idqqimg.com/wpa/images/group.png)](//shang.qq.com/wpa/qunwpa?idkey=e716eeb7834cf2083bccaea4064c8edee735d010c6a4c032835020e8fb1e0139)
- 本地直接搭建 [gitbook](https://github.com/GitbookIO/gitbook)
