### ISSUE TITLE
Call to undefined method swoole_http_response::gzip()

### ISSUE THREAD

**Issue by wuchuguang** [pinguo/php-msf#147]
/Base/Output.php;296:Call to undefined method swoole_http_response::gzip()

php --ri swoole ：报以上错误
swoole

swoole support => enabled
Version => 1.9.23
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
[root@localhost etc]#

**Comment by shellvon** [comment]
@wuchuguang 你好，这个错误您应该看 `swoole` 的[文档](https://wiki.swoole.com/wiki/page/410.html):
> gzip功能依赖zlib库，在编译swoole时底层会检测系统是否存在zlib，如果不存在，gzip方法将不可用。

从你的终端输出结果您并没有安装`zlib`库
