### ISSUE TITLE
后面有没有考虑添加服务注册发现，熔断等特性？

### ISSUE THREAD

**Issue by godtail** [pinguo/php-msf#148]
看了下整个项目的思路：
1. 使用swoole异步IO提升效率
2. 使用协程提升回调效率，避免callback hell
3. 使用对象池减少内存占用

收益良多，感谢~

但感觉目前没有服务注册发现&熔断等特性，如果直接写死ip的话，感觉不利于维护和扩展，后面有考虑加上这一块吗？

**Comment by pinguo-niulingyun** [comment]
会考虑
