### ISSUE TITLE
启动服务报错了，server.php中的require_once报错

### ISSUE THREAD

**Issue by lvjing0920** [pinguo/php-msf#176]
PHP Fatal error:  require_once(): Failed opening required '/usr/local/src/msf/vendor/autoload.php' (include_path='.:/www/server/php/71/lib/php') in /usr/local/src/msf/server.php on line 19

Fatal error: require_once(): Failed opening required '/usr/local/src/msf/vendor/autoload.php' (include_path='.:/www/server/php/71/lib/php') in /usr/local/src/msf/server.php on line 19

安装完项目中并没有vendor文件夹啊，需要怎么处理，忘大神们指点~~

**Comment by shellvon** [comment]
`composer install` 一下依赖。建议你看看 `composer`
