### ISSUE TITLE
getObject通过对象池生成对象

### ISSUE THREAD

**Issue by wuchuguang** [pinguo/php-msf#64]
不是很理解它的价值，因为
class BaseModel extends Model{
   public function __constrance(){
      echo "BaseModel";
   }
}

Controller里getObject(BaseModel::class,);两次，都会打印BaseModel,也就是说，第一次生成的object，第二次还是生成object.

**Comment by pinguo-niulingyun** [comment]
主要价值有：
1. 在常驻内存进程的情况下，维持一定数量的对象，防止PHP不停的new Object带来的内存泄漏问题。
2. 方便上下文的传递，某一请求的上下文需要在不同的对象间传递的时候，因为对象池支持aop，可以实现属性注入。
