### ISSUE TITLE
extends Core / use MI 该怎么用。

### ISSUE THREAD

**Issue by wuchuguang** [pinguo/php-msf#69]
extends Core能 $this->getConfig()->get($key);

use Mi没有。

**Comment by pinguo-niulingyun** [comment]
sorry，没太懂你的意思。。。core是个基类， MI 是一个trait，提供了一些公共的代码tag。如果想交流更多，请加入QQ群讨论，github issues不太方便也不太适合讨论这些内容。。。

**Comment by wuchuguang** [comment]
好的
