### ISSUE TITLE
Redis 命令rpoplpush，brpoplpush第二个参数值始终为2

### ISSUE THREAD

**Issue by Sorci** [pinguo/php-msf#73]
src/Pools/CoroutineRedisProxy.php中第194行：
`$arguments[2] = $this->generateUniqueKey(2);`
按照generateUniqueKey函数定义，第二个参数始终为2，导致以上命令无法正常使用。
`1507708689.923708 [0 127.0.0.1:37236] "RPOPLPUSH" "sourceMQS" "2"`

**Comment by pinguo-niulingyun** [comment]
#74 这个pr来修复
