### ISSUE TITLE
getObject()//第二参数的传值。是怎么实现的。

### ISSUE THREAD

**Issue by wuchuguang** [pinguo/php-msf#75]
Pool.php类的get()//没见到this->getObject(Class, Params);//没见到Params的传值。
$reflector         = new \ReflectionClass($poolName);
            $obj               = $reflector->newInstanceWithoutConstructor();
            $obj->__useCount   = 0;
            $obj->__genTime    = time();
            $obj->__isContruct = false;
            $obj->__DSLevel    = Marco::DS_PUBLIC;

**Comment by xudianyang** [comment]
通过php-aop实现的，可以查看PG\MSF\Base\AOPFactory::getObjectPool()
