### ISSUE TITLE
plates模板上自定义函数里面无法使用连接池等的问题

### ISSUE THREAD

**Issue by shulinqian** [pinguo/php-msf#99]
paltes模板可以自定义函数，一般用于一些页面助手函数和挂件，
http://platesphp.com/engine/functions/
但是这些函数里面无法使用 数据库,reids等

**Comment by pinguo-niulingyun** [comment]
建议在逻辑层准备好数据，只在模板做输出，不建议在模板层做任何的复杂逻辑。
